The "Account Link" update
poggit-orphanage/SimpleAuth pull request #2
Opened 2017-09-13 00:34 UTC by Awzaw

This breaks getPlayer(IPlayer $player) : array by changing it to getPlayerData(string $playername) mainly because sending the Player object is impractical when modifying the Player itself. Also because anything called getPlayer() should... get a player, not an array. The BC break is reflected in a major version bump.

MySql, yaml and sqlite are all fully working, including antihack and account linking/unlinking.
The dreaded "you don't have permission to login" and register is also fixed by adapting some code from SimpleAuthHelper - which is still compatible.

2017-09-13 03:20 UTC, SOF3 commented
For Player::setName(), would it be better to use reflections?

2017-09-13 03:22 UTC, SOF3 commented
Also, what about plugins that assume Player->getName() returns a consistent value? Many other references won't be updated.

2017-09-14 06:51 UTC, SOF3 commented
Also consider using DataPacketReceiveEvent to change the username.

2017-09-14 07:45 UTC, Awzaw commented
I don't think we'll get a setName()  function, but Player::$username could be made accessible via PlayerPreLoginEvent, from what I understand - where could it use reflection, and how? As for plugins expecting a consistent value, I don't think that's a problem as the change happens early  enough during authentication and  I'm prompting the user to relog  instead of changing $username on the fly - I also tried using transfer and kick, but both have severe drawbacks. Authentication by 'lastip' (UUID) also works well with account linking.  I'll look into using DataPacketReceiveEvent.

2017-09-14 07:54 UTC, SOF3 commented
If other plugins already use the name before SimpleAuth does, it will still have a problem.

2017-09-15 04:12 UTC, SOF3 requested changes

2017-09-15 04:12 UTC, SOF3 commented on src/SimpleAuth/EventListener.php
> +                return true;
Why?

2017-09-15 11:36 UTC, Awzaw commented on src/SimpleAuth/EventListener.php
> +                return true;
fixed, thanks

2017-09-30 20:12 UTC, closed without merging